### ISSUE TITLE
Use openwisp admin_theme from openwisp-utils

### ISSUE THREAD

**Issue by rohithasrk** [openwisp/django-netjsonconfig#60]
With openwisp-utils being launched, all the shared code of openwisp-modules can be safely removed and used from the package.

**Comment by nemesisdesign** [comment]
The since the openwisp theme is a minimal django app that can be simply configured from the settings, here it can be simply removed because it's not a strictly required dependency.

I did put it here in February because I needed to do it quickly before presenting [OpenWISP 2 at FOSDEM](https://fosdem.org/2017/schedule/event/openwisp2/) and didn't have time to create something like openwisp-utils, but now thanks to your work we can clean that technical debt!
